<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DMCShop.Tests.Unit</RootNamespace>
    <AssemblyName>DMCShop.Tests.Unit</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DMCShop.Domain\DMCShop.Domain.csproj" />
    <ProjectReference Include="..\..\src\DMCShop.Providers\DMCShop.Providers.csproj" />
    <ProjectReference Include="..\..\src\DMCShop.Search\DMCShop.Search.csproj" />
  </ItemGroup>

</Project>
